apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ include "praeco-elastalert-ui.fullname" . }}
  labels:
{{ include "praeco-elastalert-ui.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "praeco-elastalert-ui.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "praeco-elastalert-ui.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "praeco-elastalert-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: nginx-conf
              mountPath: '/etc/nginx/nginx.conf'
              subPath: nginx.conf
            - name: default-conf
              mountPath: '/etc/nginx/conf.d/default.conf'
              subPath: default.conf
            - name: praeco-elastalert-ui-config
              mountPath: '/var/www/html/praeco-elastalert-ui.config.json'
              subPath: praeco-elastalert-ui.config.json
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ template "praeco-elastalert-ui.fullname" . }}-nginx-config
            items:
            - key: nginx_config
              path: nginx.conf
        - name: default-conf
          configMap:
            name: {{ template "praeco-elastalert-ui.fullname" . }}-nginx-default-config
            items:
            - key: nginx_config_default
              path: default.conf
        - name: praeco-elastalert-ui-config
          configMap:
            name: {{ template "praeco-elastalert-ui.fullname" . }}-config
            items:
            - key: praeco-elastalert-ui_config
              path: praeco-elastalert-ui.config.json