apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "praecoElastalertUI.fullname" . }}-config
  labels:
{{ include "praecoElastalertUI.labels" . | indent 4 }}
data:
  praeco-elastalert-ui-config: |-
    {
      "appUrl": "{{ .Values.praecoElastalertUI.schema }}://{{ .Values.praecoElastalertUI.external_host }}:{{ .Values.praecoElastalertUI.port }}",
      "errorLoggerUrl": "",
      "hidePreconfiguredFields": []
    }