apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "praeco-elastalert-ui.fullname" . }}-config
  labels:
    app: {{ template "praeco-elastalert-ui.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  praeco-elastalert-ui_config: |-
    {
      "appUrl": "{{ .Values.praeco-elastalert-ui.schema }}://{{ .Values.praeco-elastalert-ui.external_host }}:{{ .Values.praeco-elastalert-ui.port }}",
      "errorLoggerUrl": "",
      "hidePreconfiguredFields": []
    }