{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "praeco-elastalert-ui.serviceAccountName" . }}
  labels:
{{ include "praeco-elastalert-ui.labels" . | indent 4 }}
{{- end -}}