{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "praeco_elastalert_ui.serviceAccountName" . }}
  labels:
{{ include "praeco_elastalert_ui.labels" . | indent 4 }}
{{- end -}}